#pragma once
enum ASTKind {
    NUMBER_EXPR,
    VARIABLE_EXPR,
    BINARY_EXPR,
    CALL_EXPR,
    GLOBAL,
    FUNCTION_SIGNATURE,
    FUNCTION,
    BLOCK,
    VARIABLE_DECL,
    STRUCT_DECL,
    FOR_STATEMENT,
    WHILE_STATEMENT,
    IF_STATEMENT,
};

#define TYPE_BASIC_DOUBLE "double"
#define TYPE_BASIC_INT "int"

enum ConstantType{
    CONSTANT_REAL,
    CONSTANT_INT,
};

enum DescriptorType{
    DESCRIPTOR_BASIC,
    DESCRIPTOR_VARIABLE,
    DESCRIPTOR_STRUCT,
};